### ISSUE TITLE
A user in unable to edit his/her own work after review

### ISSUE THREAD

**Issue by anusharanganathan** [CottageLabs/willow#222] opened 2017-08-19 01:28 UTC
With the current [mediated deposit workflow](https://github.com/CottageLabs/willow/blob/master/willow/config/workflows/mediated_deposit_workflow.json), works (articles and datasets) cannot be edited once submitted and approved.

Would we like to change how this works to
 \- a user should be able to edit his/her own work after review and re-open the review process

**Comment by Nimphal** [comment] 2017-08-21 10:28
Yes, it makes sense for the depositor of the work to be able to make the requested changes.

**Comment by emanuil-tolev** [comment] 2017-08-22 09:48
ETA on fix requested by RDSS team.

**Comment by emanuil-tolev** [comment] 2017-08-22 09:48
~~fix~~ this feature

**Comment by emanuil-tolev** [comment] 2017-08-30 16:26
Let's ask Hyrax whether that is actually intended behaviour. Customising the intended workflow behaviour should only be done after some requirements gathering with the HEIs. @martyn-w and I think this is how it's intended to work. Changes can be submitted via the Contact page, there's a topic for it.

**Comment by emanuil-tolev** [comment] 2017-09-04 17:54
Wise Hyrax says:

Bess Sadler [4:18 PM] 
@emanuil You could customize the workflow. You could not remove edit access for the depositor after approval, for example.

[4:18] 
@emanuil Or you could give them comment access, so they could suggest changes but not actually edit

Perhaps we should double check https://github.com/CottageLabs/willow/blob/0e8d40609655a1daa9a1a35aec82070352647cdb/willow/config/workflows/mediated_deposit_workflow.json

**Comment by emanuil-tolev** [comment] 2017-09-05 20:14
From Hyrax slack If you don't like this feature, you could remove this line from your workflow configuration: https://github.com/CottageLabs/willow/blob/0e8d40609655a1daa9a1a35aec82070352647cdb/willow/config/workflows/mediated_deposit_workflow.json#L51 Not :100: sure what the side effects would be, if any.

**Comment by Nimphal** [comment] 2017-09-12 10:35
Closing, this is intended behaviour.

**Closed by Nimphal** 2017-09-12 10:35 UTC
Labels: must
