### ISSUE TITLE
Error creating Dataset work

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/willow#169] opened 2017-06-19 10:56 UTC
On creating a Dataset work (actually hitting "Save", not loading the dataset submission page), there is an error which says:

remote_files is not an attribute of Dataset

I looked at the Dataset object, and wasn't sure how to alter it, but I tried adding a property called :remote_files which was basically a copy of the Relation property.  When I tried to use this, it complained of

uninitialized constant VOCAB::DC

Probably this second error was because I'd messed with the Dataset file, but not sure.

**Comment by anusharanganathan** [comment] 2017-06-19 23:20
This is a known Sufia bug. See https://groups.google.com/forum/#!searchin/samvera-tech/sufia$207.2.0$20problem$20creating$20works%7Csort:relevance/samvera-tech/xUdn2mCWCys/hWy0dPlRAQAJ.

As described in there, I usually see it in dev mode and is caused by me making chages to files but not restarting the rails server.

**Comment by martyn-w** [comment] 2017-06-23 18:22
This is really an issue with how we mount the code in development mode, rather than a bug with the system. If it crops up again, simply restart Willow. Closing for now.

**Closed by martyn-w** 2017-06-23 18:22 UTC
Labels: bug, must
