### ISSUE TITLE
On viewing Administrative Sets in the admin area, this error occurs

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/willow#171] opened 2017-06-19 14:41 UTC
NoMethodError in Sufia::Admin::AdminSets#index

**Comment by anusharanganathan** [comment] 2017-06-28 21:43
Not able to reproduce it.

**Comment by Nimphal** [comment] 2017-07-03 11:43
This doesn't seem to be a problem anymore, closing.

**Closed by Nimphal** 2017-07-03 11:43 UTC
Labels: bug, must
